services:
  backend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - PGUSER=oclock
      - PGHOST=database
      - PGDATABASE=poudlard
      - PGPASSWORD=oclock
      - PGPORT=5432
    command: npm run docker
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=oclock
      - POSTGRES_PASSWORD=oclock
      - POSTGRES_DB=poudlard
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U oclock -d poudlard" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://staub.pro:3000
    ports:
      - "5173:5173"
    command: npm run dev -- --host
